26 global variables
EvoEsports/ManiaTemplates pull request #39
Opened 2023-11-11 14:27 UTC by araszka

2023-11-12 16:47 UTC, snixtho requested changes

2023-11-12 16:47 UTC, snixtho commented on src/ManiaTemplates/ManiaTemplateEngine.cs
> +    public Task SetGlobalVariable(string key, object value)
Perhaps its a better idea to use properties for these instead of methods? Seems unecessary.

2023-11-16 11:39 UTC, kdankert approved these changes
Looks fine for me. We should think about how to handle multiple registrations of the same global variable name though. A simple warning might be sufficient.

2023-11-16 18:17 UTC, snixtho approved these changes

2023-11-16 18:18 UTC, merged